// Mocks generated by Mockito 5.4.5 from annotations
// in docjet_mobile/test/features/jobs/data/repositories/job_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:docjet_mobile/features/jobs/data/datasources/job_local_data_source.dart'
    as _i5;
import 'package:docjet_mobile/features/jobs/data/datasources/job_remote_data_source.dart'
    as _i3;
import 'package:docjet_mobile/features/jobs/data/models/job_hive_model.dart'
    as _i6;
import 'package:docjet_mobile/features/jobs/domain/entities/job.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeJob_0 extends _i1.SmartFake implements _i2.Job {
  _FakeJob_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [JobRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobRemoteDataSource extends _i1.Mock
    implements _i3.JobRemoteDataSource {
  MockJobRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Job>> fetchJobs() => (super.noSuchMethod(
        Invocation.method(
          #fetchJobs,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Job>>.value(<_i2.Job>[]),
      ) as _i4.Future<List<_i2.Job>>);

  @override
  _i4.Future<_i2.Job> fetchJobById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #fetchJobById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Job>.value(_FakeJob_0(
          this,
          Invocation.method(
            #fetchJobById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Job>);

  @override
  _i4.Future<_i2.Job> createJob({
    required String? userId,
    required String? audioFilePath,
    String? text,
    String? additionalText,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createJob,
          [],
          {
            #userId: userId,
            #audioFilePath: audioFilePath,
            #text: text,
            #additionalText: additionalText,
          },
        ),
        returnValue: _i4.Future<_i2.Job>.value(_FakeJob_0(
          this,
          Invocation.method(
            #createJob,
            [],
            {
              #userId: userId,
              #audioFilePath: audioFilePath,
              #text: text,
              #additionalText: additionalText,
            },
          ),
        )),
      ) as _i4.Future<_i2.Job>);

  @override
  _i4.Future<_i2.Job> updateJob({
    required String? jobId,
    required Map<String, dynamic>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateJob,
          [],
          {
            #jobId: jobId,
            #updates: updates,
          },
        ),
        returnValue: _i4.Future<_i2.Job>.value(_FakeJob_0(
          this,
          Invocation.method(
            #updateJob,
            [],
            {
              #jobId: jobId,
              #updates: updates,
            },
          ),
        )),
      ) as _i4.Future<_i2.Job>);
}

/// A class which mocks [JobLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobLocalDataSource extends _i1.Mock
    implements _i5.JobLocalDataSource {
  MockJobLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i6.JobHiveModel>> getAllJobHiveModels() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllJobHiveModels,
          [],
        ),
        returnValue:
            _i4.Future<List<_i6.JobHiveModel>>.value(<_i6.JobHiveModel>[]),
      ) as _i4.Future<List<_i6.JobHiveModel>>);

  @override
  _i4.Future<_i6.JobHiveModel?> getJobHiveModelById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJobHiveModelById,
          [id],
        ),
        returnValue: _i4.Future<_i6.JobHiveModel?>.value(),
      ) as _i4.Future<_i6.JobHiveModel?>);

  @override
  _i4.Future<void> saveJobHiveModel(_i6.JobHiveModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveJobHiveModel,
          [model],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveJobHiveModels(List<_i6.JobHiveModel>? models) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveJobHiveModels,
          [models],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteJobHiveModel(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteJobHiveModel,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllJobHiveModels() => (super.noSuchMethod(
        Invocation.method(
          #clearAllJobHiveModels,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i6.JobHiveModel?> getLastJobHiveModel() => (super.noSuchMethod(
        Invocation.method(
          #getLastJobHiveModel,
          [],
        ),
        returnValue: _i4.Future<_i6.JobHiveModel?>.value(),
      ) as _i4.Future<_i6.JobHiveModel?>);
}
