name: devicesyslog_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  ansicolor: ^2.0.3

dev_dependencies:
  coverage: ^1.13.1
  lints: ^5.0.0
  mockito: ^5.4.6
  test: ^1.25.15

executables:
  devicesyslog: devicesyslog
