name: docjet_test
description: Test utilities for DocJet Mobile
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  logger: ^2.0.2+1  # Updated to match main app's version
  # Add other deps as needed

dev_dependencies:
  flutter_lints: ^2.0.0 