// Mocks generated by Mockito 5.4.5 from annotations
// in docjet_mobile/test/features/jobs/data/services/job_writer_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:docjet_mobile/features/jobs/data/datasources/job_local_data_source.dart'
    as _i5;
import 'package:docjet_mobile/features/jobs/data/models/job_hive_model.dart'
    as _i8;
import 'package:docjet_mobile/features/jobs/domain/entities/job.dart' as _i2;
import 'package:docjet_mobile/features/jobs/domain/entities/sync_status.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:uuid/data.dart' as _i10;
import 'package:uuid/uuid.dart' as _i9;
import 'package:uuid/uuid_value.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeJob_0 extends _i1.SmartFake implements _i2.Job {
  _FakeJob_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUnit_1 extends _i1.SmartFake implements _i3.Unit {
  _FakeUnit_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUuidValue_2 extends _i1.SmartFake implements _i4.UuidValue {
  _FakeUuidValue_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [JobLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobLocalDataSource extends _i1.Mock
    implements _i5.JobLocalDataSource {
  MockJobLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Job> getJobById(String? localId) => (super.noSuchMethod(
        Invocation.method(
          #getJobById,
          [localId],
        ),
        returnValue: _i6.Future<_i2.Job>.value(_FakeJob_0(
          this,
          Invocation.method(
            #getJobById,
            [localId],
          ),
        )),
      ) as _i6.Future<_i2.Job>);

  @override
  _i6.Future<_i3.Unit> saveJob(_i2.Job? job) => (super.noSuchMethod(
        Invocation.method(
          #saveJob,
          [job],
        ),
        returnValue: _i6.Future<_i3.Unit>.value(_FakeUnit_1(
          this,
          Invocation.method(
            #saveJob,
            [job],
          ),
        )),
      ) as _i6.Future<_i3.Unit>);

  @override
  _i6.Future<_i3.Unit> deleteJob(String? localId) => (super.noSuchMethod(
        Invocation.method(
          #deleteJob,
          [localId],
        ),
        returnValue: _i6.Future<_i3.Unit>.value(_FakeUnit_1(
          this,
          Invocation.method(
            #deleteJob,
            [localId],
          ),
        )),
      ) as _i6.Future<_i3.Unit>);

  @override
  _i6.Future<List<_i2.Job>> getJobsByStatus(_i7.SyncStatus? status) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJobsByStatus,
          [status],
        ),
        returnValue: _i6.Future<List<_i2.Job>>.value(<_i2.Job>[]),
      ) as _i6.Future<List<_i2.Job>>);

  @override
  _i6.Future<List<_i8.JobHiveModel>> getAllJobHiveModels() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllJobHiveModels,
          [],
        ),
        returnValue:
            _i6.Future<List<_i8.JobHiveModel>>.value(<_i8.JobHiveModel>[]),
      ) as _i6.Future<List<_i8.JobHiveModel>>);

  @override
  _i6.Future<_i8.JobHiveModel?> getJobHiveModelById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getJobHiveModelById,
          [id],
        ),
        returnValue: _i6.Future<_i8.JobHiveModel?>.value(),
      ) as _i6.Future<_i8.JobHiveModel?>);

  @override
  _i6.Future<void> saveJobHiveModel(_i8.JobHiveModel? model) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveJobHiveModel,
          [model],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> saveJobHiveModels(List<_i8.JobHiveModel>? models) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveJobHiveModels,
          [models],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> deleteJobHiveModel(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteJobHiveModel,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearAllJobHiveModels() => (super.noSuchMethod(
        Invocation.method(
          #clearAllJobHiveModels,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i8.JobHiveModel?> getLastJobHiveModel() => (super.noSuchMethod(
        Invocation.method(
          #getLastJobHiveModel,
          [],
        ),
        returnValue: _i6.Future<_i8.JobHiveModel?>.value(),
      ) as _i6.Future<_i8.JobHiveModel?>);

  @override
  _i6.Future<DateTime?> getLastFetchTime() => (super.noSuchMethod(
        Invocation.method(
          #getLastFetchTime,
          [],
        ),
        returnValue: _i6.Future<DateTime?>.value(),
      ) as _i6.Future<DateTime?>);

  @override
  _i6.Future<void> saveLastFetchTime(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #saveLastFetchTime,
          [time],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.JobHiveModel>> getJobsToSync() => (super.noSuchMethod(
        Invocation.method(
          #getJobsToSync,
          [],
        ),
        returnValue:
            _i6.Future<List<_i8.JobHiveModel>>.value(<_i8.JobHiveModel>[]),
      ) as _i6.Future<List<_i8.JobHiveModel>>);

  @override
  _i6.Future<void> updateJobSyncStatus(
    String? id,
    _i7.SyncStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateJobSyncStatus,
          [
            id,
            status,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.JobHiveModel>> getSyncedJobHiveModels() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSyncedJobHiveModels,
          [],
        ),
        returnValue:
            _i6.Future<List<_i8.JobHiveModel>>.value(<_i8.JobHiveModel>[]),
      ) as _i6.Future<List<_i8.JobHiveModel>>);
}

/// A class which mocks [Uuid].
///
/// See the documentation for Mockito's code generation for more information.
class MockUuid extends _i1.Mock implements _i9.Uuid {
  MockUuid() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String v1({
    Map<String, dynamic>? options,
    _i10.V1Options? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1,
          [],
          {
            #options: options,
            #config: config,
          },
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #v1,
            [],
            {
              #options: options,
              #config: config,
            },
          ),
        ),
      ) as String);

  @override
  List<int> v1buffer(
    List<int>? buffer, {
    Map<String, dynamic>? options,
    _i10.V1Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1buffer,
          [buffer],
          {
            #options: options,
            #config: config,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i4.UuidValue v1obj({
    Map<String, dynamic>? options,
    _i10.V1Options? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1obj,
          [],
          {
            #options: options,
            #config: config,
          },
        ),
        returnValue: _FakeUuidValue_2(
          this,
          Invocation.method(
            #v1obj,
            [],
            {
              #options: options,
              #config: config,
            },
          ),
        ),
      ) as _i4.UuidValue);

  @override
  String v4({
    Map<String, dynamic>? options,
    _i10.V4Options? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v4,
          [],
          {
            #options: options,
            #config: config,
          },
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #v4,
            [],
            {
              #options: options,
              #config: config,
            },
          ),
        ),
      ) as String);

  @override
  List<int> v4buffer(
    List<int>? buffer, {
    Map<String, dynamic>? options,
    _i10.V4Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v4buffer,
          [buffer],
          {
            #options: options,
            #config: config,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i4.UuidValue v4obj({
    Map<String, dynamic>? options,
    _i10.V4Options? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v4obj,
          [],
          {
            #options: options,
            #config: config,
          },
        ),
        returnValue: _FakeUuidValue_2(
          this,
          Invocation.method(
            #v4obj,
            [],
            {
              #options: options,
              #config: config,
            },
          ),
        ),
      ) as _i4.UuidValue);

  @override
  String v5(
    String? namespace,
    String? name, {
    Map<String, dynamic>? options,
    _i10.V5Options? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v5,
          [
            namespace,
            name,
          ],
          {
            #options: options,
            #config: config,
          },
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #v5,
            [
              namespace,
              name,
            ],
            {
              #options: options,
              #config: config,
            },
          ),
        ),
      ) as String);

  @override
  List<int> v5buffer(
    String? namespace,
    String? name,
    List<int>? buffer, {
    Map<String, dynamic>? options,
    _i10.V5Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v5buffer,
          [
            namespace,
            name,
            buffer,
          ],
          {
            #options: options,
            #config: config,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i4.UuidValue v5obj(
    String? namespace,
    String? name, {
    Map<String, dynamic>? options,
    _i10.V5Options? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v5obj,
          [
            namespace,
            name,
          ],
          {
            #options: options,
            #config: config,
          },
        ),
        returnValue: _FakeUuidValue_2(
          this,
          Invocation.method(
            #v5obj,
            [
              namespace,
              name,
            ],
            {
              #options: options,
              #config: config,
            },
          ),
        ),
      ) as _i4.UuidValue);

  @override
  String v6({_i10.V6Options? config}) => (super.noSuchMethod(
        Invocation.method(
          #v6,
          [],
          {#config: config},
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #v6,
            [],
            {#config: config},
          ),
        ),
      ) as String);

  @override
  List<int> v6buffer(
    List<int>? buffer, {
    _i10.V6Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v6buffer,
          [buffer],
          {
            #config: config,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i4.UuidValue v6obj({_i10.V6Options? config}) => (super.noSuchMethod(
        Invocation.method(
          #v6obj,
          [],
          {#config: config},
        ),
        returnValue: _FakeUuidValue_2(
          this,
          Invocation.method(
            #v6obj,
            [],
            {#config: config},
          ),
        ),
      ) as _i4.UuidValue);

  @override
  String v7({_i10.V7Options? config}) => (super.noSuchMethod(
        Invocation.method(
          #v7,
          [],
          {#config: config},
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #v7,
            [],
            {#config: config},
          ),
        ),
      ) as String);

  @override
  List<int> v7buffer(
    List<int>? buffer, {
    _i10.V7Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v7buffer,
          [buffer],
          {
            #config: config,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i4.UuidValue v7obj({_i10.V7Options? config}) => (super.noSuchMethod(
        Invocation.method(
          #v7obj,
          [],
          {#config: config},
        ),
        returnValue: _FakeUuidValue_2(
          this,
          Invocation.method(
            #v7obj,
            [],
            {#config: config},
          ),
        ),
      ) as _i4.UuidValue);

  @override
  String v8({_i10.V8Options? config}) => (super.noSuchMethod(
        Invocation.method(
          #v8,
          [],
          {#config: config},
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #v8,
            [],
            {#config: config},
          ),
        ),
      ) as String);

  @override
  List<int> v8buffer(
    List<int>? buffer, {
    _i10.V8Options? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v8buffer,
          [buffer],
          {
            #config: config,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i4.UuidValue v8obj({_i10.V8Options? config}) => (super.noSuchMethod(
        Invocation.method(
          #v8obj,
          [],
          {#config: config},
        ),
        returnValue: _FakeUuidValue_2(
          this,
          Invocation.method(
            #v8obj,
            [],
            {#config: config},
          ),
        ),
      ) as _i4.UuidValue);

  @override
  String v8g({_i10.V8GenericOptions? config}) => (super.noSuchMethod(
        Invocation.method(
          #v8g,
          [],
          {#config: config},
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #v8g,
            [],
            {#config: config},
          ),
        ),
      ) as String);

  @override
  List<int> v8gbuffer(
    List<int>? buffer, {
    _i10.V8GenericOptions? config,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v8gbuffer,
          [buffer],
          {
            #config: config,
            #offset: offset,
          },
        ),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i4.UuidValue v8gobj({_i10.V8GenericOptions? config}) => (super.noSuchMethod(
        Invocation.method(
          #v8gobj,
          [],
          {#config: config},
        ),
        returnValue: _FakeUuidValue_2(
          this,
          Invocation.method(
            #v8gobj,
            [],
            {#config: config},
          ),
        ),
      ) as _i4.UuidValue);
}
