name: mock_api_server
description: A minimal mock API server for the DocJet mobile app.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.7.0
  dart_jsonwebtoken: ^3.2.0
  mime: ^1.0.5
  path: ^1.9.0
  shelf: ^1.4.0
  shelf_multipart: ^2.0.1
  shelf_router: ^1.1.0
  uuid: ^4.5.1

dev_dependencies:
  http: ^1.1.0 
  test: ^1.24.0
  lints: ^3.0.0 
