// Mocks generated by Mockito 5.4.5 from annotations
// in docjet_mobile/test/core/auth/infrastructure/dio_factory_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:dio/dio.dart' as _i2;
import 'package:docjet_mobile/core/auth/auth_credentials_provider.dart' as _i3;
import 'package:docjet_mobile/core/auth/events/auth_event_bus.dart' as _i8;
import 'package:docjet_mobile/core/auth/events/auth_events.dart' as _i9;
import 'package:docjet_mobile/core/auth/infrastructure/authentication_api_client.dart'
    as _i6;
import 'package:docjet_mobile/core/auth/infrastructure/dtos/login_response_dto.dart'
    as _i4;
import 'package:docjet_mobile/core/auth/infrastructure/dtos/refresh_response_dto.dart'
    as _i5;
import 'package:docjet_mobile/core/interfaces/app_config_interface.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthCredentialsProvider_1 extends _i1.SmartFake
    implements _i3.AuthCredentialsProvider {
  _FakeAuthCredentialsProvider_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginResponseDto_2 extends _i1.SmartFake
    implements _i4.LoginResponseDto {
  _FakeLoginResponseDto_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRefreshResponseDto_3 extends _i1.SmartFake
    implements _i5.RefreshResponseDto {
  _FakeRefreshResponseDto_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthenticationApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationApiClient extends _i1.Mock
    implements _i6.AuthenticationApiClient {
  MockAuthenticationApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get basicHttpClient => (super.noSuchMethod(
        Invocation.getter(#basicHttpClient),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#basicHttpClient),
        ),
      ) as _i2.Dio);

  @override
  _i3.AuthCredentialsProvider get credentialsProvider => (super.noSuchMethod(
        Invocation.getter(#credentialsProvider),
        returnValue: _FakeAuthCredentialsProvider_1(
          this,
          Invocation.getter(#credentialsProvider),
        ),
      ) as _i3.AuthCredentialsProvider);

  @override
  _i7.Future<_i4.LoginResponseDto> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i7.Future<_i4.LoginResponseDto>.value(_FakeLoginResponseDto_2(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i7.Future<_i4.LoginResponseDto>);

  @override
  _i7.Future<_i5.RefreshResponseDto> refreshToken(String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [refreshToken],
        ),
        returnValue:
            _i7.Future<_i5.RefreshResponseDto>.value(_FakeRefreshResponseDto_3(
          this,
          Invocation.method(
            #refreshToken,
            [refreshToken],
          ),
        )),
      ) as _i7.Future<_i5.RefreshResponseDto>);

  @override
  void testHandleDioException(_i2.DioException? e) => super.noSuchMethod(
        Invocation.method(
          #testHandleDioException,
          [e],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthCredentialsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthCredentialsProvider extends _i1.Mock
    implements _i3.AuthCredentialsProvider {
  MockAuthCredentialsProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String?> getApiKey() => (super.noSuchMethod(
        Invocation.method(
          #getApiKey,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> setAccessToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #setAccessToken,
          [token],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> deleteAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccessToken,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setRefreshToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #setRefreshToken,
          [token],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> deleteRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteRefreshToken,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> setUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #setUserId,
          [userId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> getUserId() => (super.noSuchMethod(
        Invocation.method(
          #getUserId,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<bool> isAccessTokenValid() => (super.noSuchMethod(
        Invocation.method(
          #isAccessTokenValid,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> isRefreshTokenValid() => (super.noSuchMethod(
        Invocation.method(
          #isRefreshTokenValid,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
}

/// A class which mocks [AuthEventBus].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthEventBus extends _i1.Mock implements _i8.AuthEventBus {
  MockAuthEventBus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<_i9.AuthEvent> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i7.Stream<_i9.AuthEvent>.empty(),
      ) as _i7.Stream<_i9.AuthEvent>);

  @override
  void add(_i9.AuthEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AppConfigInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppConfigInterface extends _i1.Mock
    implements _i10.AppConfigInterface {
  MockAppConfigInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiDomain => (super.noSuchMethod(
        Invocation.getter(#apiDomain),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#apiDomain),
        ),
      ) as String);

  @override
  String get apiKey => (super.noSuchMethod(
        Invocation.getter(#apiKey),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#apiKey),
        ),
      ) as String);

  @override
  bool get isDevelopment => (super.noSuchMethod(
        Invocation.getter(#isDevelopment),
        returnValue: false,
      ) as bool);
}
